app/views/mode_view.py
# Import necessary modules
from flask import Blueprint, render_template, request, redirect, url_for, session
import sqlite3

# Create a Flask Blueprint named 'mode'
mode = Blueprint('mode', __name__)

# Define a function to initialize the modes database
def init_db():
    with sqlite3.connect('modes.db') as conn:
        cursor = conn.cursor()

        # Create the 'modes' table if it doesn't exist
        cursor.execute('''
            CREATE TABLE IF NOT EXISTS modes (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                user_id INTEGER,
                mode_name TEXT,
                background_color TEXT,
                font_family TEXT,
                note_view TEXT,
                FOREIGN KEY (user_id) REFERENCES users (id)
            )
        ''')

        # Create the 'notes' table if it doesn't exist
        cursor.execute('''
            CREATE TABLE IF NOT EXISTS notes (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                mode_id INTEGER,
                note_name TEXT,
                note_content TEXT, 
                note_password TEXT,
                FOREIGN KEY (mode_id) REFERENCES modes (id)
            )
        ''')

        conn.commit()

# Initialize the database when the application starts
init_db()

# Define a function to get the user ID based on the username
def get_user_id(username):
    conn = sqlite3.connect('users.db')
    cursor = conn.cursor()
    cursor.execute('SELECT id FROM users WHERE username = ?', (username,))
    user_id = cursor.fetchone()[0]
    conn.close()
    return user_id

# Define a route for adding a new mode
@mode.route('/add-mode', methods=['GET', 'POST'])
def add_mode():
    if request.method == 'POST':
        # Get mode details from the form
        mode_name = request.form.get('mode_name')
        background_color = request.form.get('background_color')
        font_family = request.form.get('font_family')
        note_view = 'note-tile'

        if 'username' in session:
            username = session['username']

            # Get user id
            user_id = get_user_id(username)

            # Insert new mode into the database with auto-incremented id
            with sqlite3.connect('modes.db') as conn:
                cursor = conn.cursor()
                cursor.execute('INSERT INTO modes (user_id, mode_name, background_color, font_family, note_view) VALUES (?, ?, ?, ?, ?)',
                               (user_id, mode_name, background_color, font_family, note_view))
                mode_id = cursor.lastrowid

            return redirect(url_for('mode.list_modes'))

    return render_template('add_mode.html')

# Define a route for listing modes on the home page
@mode.route('/home', methods=['GET', 'POST'])
def list_modes():
    if 'username' in session:
        username = session['username']
        print(f"Username: {username}")

        # Get user id
        user_id = get_user_id(username)
        print(f"User ID: {user_id}")

        # Retrieve modes for the user from the database
        with sqlite3.connect('modes.db') as conn:
            cursor = conn.cursor()
            cursor.execute('SELECT * FROM modes WHERE user_id = ?', (user_id,))
            modes = cursor.fetchall()
            for mode in modes:
                print(f"Mode_name: {mode[2]}, Background Color: {mode[3]}, Font Family: {mode[4]}")

        return render_template('home.html', modes=modes)

    return redirect(url_for('login'))

# Helper function to get mode details by ID
def get_mode_by_id(mode_id):
    with sqlite3.connect('modes.db') as conn:
        cursor = conn.cursor()
        cursor.execute('SELECT * FROM modes WHERE id = ?', (mode_id,))
        mode = cursor.fetchone()
    return mode

# Helper function to update mode details by ID
def update_mode(mode_id, mode_name, background_color, font_family, note_view):
    with sqlite3.connect('modes.db') as conn:
        cursor = conn.cursor()
        cursor.execute('UPDATE modes SET mode_name = ?, background_color = ?, font_family = ?, note_view = ? WHERE id = ?',
                       (mode_name, background_color, font_family, note_view, mode_id))
        conn.commit()

# Define a route for editing a mode
@mode.route('/edit-mode/<int:mode_id>', methods=['GET', 'POST'])
def edit_mode(mode_id):
    if 'username' in session:
        username = session['username']
        user_id = get_user_id(username)

        # Get mode details by ID
        mode = get_mode_by_id(mode_id)

        if request.method == 'POST':
            # Update mode details
            mode_name = request.form.get('mode_name')
            background_color = request.form.get('background_color')
            font_family = request.form.get('font_family')
            note_view = request.form.get('note_view')
            delete_mode = request.form.get('deleteMode')  # Check if the checkbox is selected

            if delete_mode is not None:  # Check if the checkbox is selected
                # Delete the mode if the checkbox is selected
                with sqlite3.connect('modes.db') as conn:
                    cursor = conn.cursor()
                    cursor.execute('DELETE FROM modes WHERE id = ? AND user_id = ?', (mode_id, user_id))
                return redirect(url_for('mode.list_modes'))
            else:
                # Update mode details if the checkbox is not selected
                update_mode(mode_id, mode_name, background_color, font_family, note_view)
                return redirect(url_for('mode.list_modes'))

        return render_template('edit_mode.html', mode=mode)

    return redirect(url_for('login'))

app/views/note_editer_view.py
import sqlite3
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from flask import Blueprint, render_template
from views.note_view import get_mode_info, get_mode_by_id, get_background_color, get_note_by_id, request

note = Blueprint('note', __name__)


# this route shows the note and updates the styling according to its mode, it also request a password to be entered,
# if a password is associted to the note 
@note.route('/mode/<int:mode_id>/notes/<int:note_id>')
def show_note(mode_id, note_id):
    
    color = get_background_color(mode_id)
    name = get_note_by_id(note_id)
    password = get_note_password(note_id)

    if password is not None: 
        return render_template('password_prompt.html', mode_id=mode_id, note_id=note_id) # if password is needed then prompt the user 

    return render_template('note.html', color=color, name=name)

# route for the notfication to be sent
@note.route('/mode/<int:mode_id>/notes/<int:note_id>/notifications', methods=['GET', 'POST'])
def notifications(mode_id, note_id):
    color = get_background_color(mode_id)
    name = get_note_by_id(note_id)
    password = get_note_password(note_id)

    
    if request.method == 'POST':
        email = request.form['email']
        selected_date = request.form['selected_date']

        # Gmail credentials
        gmail_user = 'notemode4@gmail.com'
        gmail_password = 'ggtunleyylvgkkvo'

        # Set up the email content
        subject = f'NoteMode Reminder for {selected_date} your note called: {name[2]}'
        body = f'Hello,\n\nThis is a reminder for the selected date: "{selected_date}: in your note: "{name[2]}".\n\nBest regards,\n NoteMode'

        message = MIMEMultipart()
        message['From'] = gmail_user
        message['To'] = email
        message['Subject'] = subject
        message.attach(MIMEText(body, 'plain'))

        # Connect to Gmail SMTP server
        with smtplib.SMTP('smtp.gmail.com', 587) as server:
            server.starttls()
            server.login(gmail_user, gmail_password)
            server.sendmail(gmail_user, email, message.as_string())

            return render_template('note.html', color=color, name=name)

    return render_template('notifications.html', mode_id=mode_id, note_id=note_id)


# route for a password to be written to get in a note 
@note.route('/mode/<int:mode_id>/notes/<int:note_id>', methods=['GET', 'POST'])
def password_note(mode_id, note_id):
    color = get_background_color(mode_id)
    name = get_note_by_id(note_id)
    password = get_note_password(note_id)

    if request.method == 'POST':
        entered_password = request.form.get('note_password')

        if entered_password == password:
            # Password is correct, continue to show the note content
            return render_template('note.html', color=color, name=name)
        else:
            # Incorrect password, show an error message
            error_message = 'Incorrect password. Please try again.'
            return render_template('password_prompt.html', mode_id=mode_id, note_id=note_id, error_message=error_message)


    return render_template('password_prompt.html', mode_id=mode_id, note_id=note_id)


# the route that counts the words in a note
@note.route('/mode/<int:mode_id>/notes/<int:note_id>')
def word_count(s):  
    if request.method == 'POST':
        note_content = request.form.get('noteTextarea')
        word_count = count_words(note_content)
        return render_template('note.html', word_count=word_count)
    else: 
        return render_template('note.html')
    
# helper function fo counter the words in a note 
def count_words(text):
    words = text.split()
    return len(words)

# helper function for note password 
def get_note_password(note_id):
    with sqlite3.connect('modes.db') as conn:
        cursor = conn.cursor()
        cursor.execute('SELECT note_password FROM notes WHERE id = ?', (note_id,))
        note_password = cursor.fetchone()
    return note_password[0] if note_password else None

app/views/note_view.py
from flask import Blueprint, render_template, redirect, url_for, session, flash, request
from views.mode_view import get_user_id, get_mode_by_id
import sqlite3
from views.mode_view import get_user_id

# Create a Flask Blueprint named 'notes'
notes = Blueprint('notes', __name__)

# Define a route to show notes for a specific mode
@notes.route('/mode/<int:mode_id>/notes')
def show_notes(mode_id):
    if 'username' in session:
        username = session['username']
        user_id = get_user_id(username)

        # Get notes and mode details
        notes = get_notes_by_mode(mode_id)
        color = get_background_color(mode_id)
        font = get_font(mode_id)
        view = get_view(mode_id)
        name = get_mode_name(mode_id)

    
        # Render the notes template with mode information
        return render_template('notes.html', name=name, color=color, font=font, mode_id=mode_id, view=view, notes=notes)

    return redirect(url_for('login'))

# Define a route to add a new note for a specific mode
@notes.route('/mode/<int:mode_id>/add-note', methods=['GET', 'POST'])
def add_note(mode_id):
    if 'username' in session:
        username = session['username']
        user_id = get_user_id(username)

        mode = get_mode_by_id(mode_id)

        if request.method == 'POST':
            # Get note name from the form
            note_name = request.form.get('note_name')

            # Insert new note into the database
            with sqlite3.connect('modes.db') as conn:
                cursor = conn.cursor()
                cursor.execute('INSERT INTO notes (mode_id, note_name) VALUES (?, ?)', (mode_id, note_name))
                conn.commit()

            flash('Note added successfully!', 'success')
            return redirect(url_for('notes.show_notes', mode_id=mode_id))

        return render_template('add_note.html', mode=mode)

    return redirect(url_for('login'))

# Define a route to edit a note for a specific mode
@notes.route('/mode/<int:mode_id>/edit-note/<int:note_id>', methods=['GET', 'POST'])
def edit_note(mode_id, note_id):
    if 'username' in session:
        username = session['username']
        user_id = get_user_id(username)

        note = get_note_by_id(note_id)

        if request.method == 'POST':
            # Get new note name and check if the checkbox is selected for deletion
            new_note_name = request.form.get('note_name')
            delete_note = request.form.get('deleteNote')
            protectNote = request.form.get('protectNote')
            note_password = request.form.get('note_password')

            if protectNote is not None:  
                with sqlite3.connect('modes.db') as conn:
                    cursor = conn.cursor()
                    cursor.execute('UPDATE notes SET note_password = ? WHERE id = ?', (note_password, note_id))
                    conn.commit()
                return redirect(url_for('notes.show_notes', mode_id=mode_id))


            if delete_note is not None:  # Check if the checkbox is selected
                # Delete the note if the checkbox is selected
                with sqlite3.connect('modes.db') as conn:
                    cursor = conn.cursor()
                    cursor.execute('DELETE FROM notes WHERE id = ?', (note_id,))
                    conn.commit()
                return redirect(url_for('notes.show_notes', mode_id=mode_id))

            # Update note details if the checkbox is not selected
            with sqlite3.connect('modes.db') as conn:
                cursor = conn.cursor()
                cursor.execute('UPDATE notes SET note_name = ? WHERE id = ?', (new_note_name, note_id))
                conn.commit()

            return redirect(url_for('notes.show_notes', mode_id=mode_id))

        return render_template('edit_note.html', note=note, mode_id=mode_id, note_id=note_id)

    return redirect(url_for('login'))

# route for saving a note in a mode
@notes.route('/mode/<int:mode_id>/edit-note/<int:note_id>/save-note', methods=['GET', 'POST'])
def save_note(mode_id, note_id):
    if 'username' in session:
        username = session['username']
        user_id = get_user_id(username)

        note = get_note_by_id(note_id)

        if request.method == 'POST':
            # Get note content from CKEditor
            note_content = request.form.get('content')

            # Update existing note in the database
            with sqlite3.connect('modes.db') as conn:
                cursor = conn.cursor()
                cursor.execute('UPDATE notes SET note_content = ? WHERE id = ?', (note_content, note_id))
                conn.commit()

            flash('Note updated successfully!', 'success')

            return redirect(url_for('notes.show_notes', mode_id=mode_id))

        return render_template('note.html', note=note, mode_id=mode_id, note_id=note_id)

    return redirect(url_for('login'))


# Helper function to get mode information by ID
def get_mode_info(mode_id):
    with sqlite3.connect('modes.db') as conn:
        cursor = conn.cursor()
        cursor.execute('SELECT * FROM modes WHERE id = ?', (mode_id,))
        mode_info = cursor.fetchone()
    return mode_info

# Helper function to get background color by mode ID
def get_background_color(mode_id):
    with sqlite3.connect('modes.db') as conn:
        cursor = conn.cursor()
        cursor.execute('SELECT background_color FROM modes WHERE id = ?', (mode_id,))
        background_color = cursor.fetchone()
    return background_color[0] if background_color else None

# Helper function to get font by mode ID
def get_font(mode_id):
    with sqlite3.connect('modes.db') as conn:
        cursor = conn.cursor()
        cursor.execute('SELECT font_family FROM modes WHERE id = ?', (mode_id,))
        font = cursor.fetchone()
    return font[0] if font else None

# Helper function to get note view by mode ID
def get_view(mode_id):
    with sqlite3.connect('modes.db') as conn:
        cursor = conn.cursor()
        cursor.execute('SELECT note_view FROM modes WHERE id = ?', (mode_id,))
        view = cursor.fetchone()  
    return view[0] if view else None

# Helper function to get mode name by mode ID
def get_mode_name(mode_id):
    with sqlite3.connect('modes.db') as conn:
        cursor = conn.cursor()
        cursor.execute('SELECT mode_name FROM modes WHERE id = ?', (mode_id,))
        mode_name = cursor.fetchone()
    return mode_name[0]

# Helper function to get notes by mode ID
def get_notes_by_mode(mode_id):
    conn = sqlite3.connect('modes.db')
    cursor = conn.cursor()
    cursor.execute('SELECT * FROM notes WHERE mode_id = ?', (mode_id,))
    notes = cursor.fetchall()
    conn.close()
    print(notes)
    return notes

# Helper function to get note by ID
def get_note_by_id(note_id):
    with sqlite3.connect('modes.db') as conn:
        cursor = conn.cursor()
        cursor.execute('SELECT * FROM notes WHERE id = ?', (note_id,))
        note = cursor.fetchone()
    return note

app/templates/add_mode.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Meta tags for character set and viewport settings -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <!-- Links to Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />

    <!-- Link to external CSS file -->
    <link href="../static/add_mode.css" rel="stylesheet" type="text/css" />
    
    <!-- Title of the HTML page -->
    <title>NoteMode</title>
</head>
<body>

    <!-- Header section with mode information -->
    <h1 class="mode-header">Create Mode</h1>
    <div id="line"></div>

    <!-- Link to navigate back to the home page -->
    <a href="{{ url_for('home')}}">
        <span class="material-symbols-outlined" id="arrowBack">
            arrow_back
        </span>
    </a>

    <!-- Form section for creating a mode -->
    <div class="create-mode-form">
        <form method="post" action="{{ url_for('mode.add_mode') }}">
            <label for="mode_name">Mode Name:</label>
            <input type="text" id="mode_name" name="mode_name" maxlength="15" required><br>
            <!-- Button to submit the form and create the mode -->
            <div id="buttonContainer">
                <button type="submit">Create</button>
            </div>
        </form>
    </div>

    <!-- Link to navigate to the settings page -->
    <a href="{{ url_for('settings.settings_page') }}">
        <span class="material-symbols-outlined" id="btnSetting">settings</span>
    </a>

</body>
</html>

app/templates/add_note.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Meta tags for character set and viewport settings -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Links to Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />

    <!-- Link to external CSS file using Flask's url_for method -->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='add_mode.css') }}">

    <!-- Title of the HTML page -->
    <title>NoteMode</title>
</head>
<body>

    <!-- Header section with note creation information -->
    <h1 class="mode-header">Create Note</h1>
    <div id="line"></div>

    <!-- Link to navigate back to the notes page -->
    <a href="{{ url_for('notes.show_notes', mode_id=mode[0]) }}">
        <span class="material-symbols-outlined" id="arrowBack">
            arrow_back
        </span>
    </a>

    <!-- Form section for creating a note -->
    <div class="create-mode-form">
        <form method="POST" action="{{ url_for('notes.add_note', mode_id=mode[0]) }}">
            <label for="note_name">Note Name:</label>
            <input type="text" id="note_name" name="note_name" maxlength="15" required>
            <!-- Button to submit the form and create the note -->
            <button type="submit">Create</button>
        </form>
    </div>

    <!-- Link to navigate to the settings page -->
    <a href="{{ url_for('settings.settings_page') }}">
        <span class="material-symbols-outlined" id="btnSetting">settings</span>
    </a>

</body>
</html>

app/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Meta tags for character set and viewport settings -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Links to Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    
    <!-- Link to external CSS file using Flask's url_for method -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <link href="../static/home.css" rel="stylesheet" type="text/css" />

    <!-- Title of the HTML page -->
    <title>NoteMode</title>
</head>
<body>

    <!-- Header section for displaying modes -->
    <h1 class="mode-header">Modes</h1>
    <div id="line"></div>

    <!-- Link to navigate to the settings page -->
    <a href="{{ url_for('settings.settings_page') }}">
        <span class="material-symbols-outlined" id="btnSetting">settings</span>
    </a>
    
    <!-- Container for displaying list of modes -->
    <div class="mode-list">
        <!-- Create new mode section -->
        <div id="createNewMode">
            <!-- Link to add a new mode -->
            <a href="{{ url_for('mode.add_mode') }}">
                <span class="material-symbols-outlined" id="btnAdd">add_circle</span> 
            </a>
            <!-- Header for creating a new mode -->
            <h4 id="createNewModeHeader"> Create New Mode </h4>
        </div>

        <!-- Loop to display existing modes -->
        {% if modes %}
            {% for mode in modes %}
                <div class="mode">
                    <!-- Link to navigate to notes in the mode -->
                    <a href="{{ url_for('notes.show_notes', mode_id=mode[0]) }}">
                        <span class="material-symbols-outlined" id="btnAdd"></span> 
                    </a>
                    <!-- Header for the mode with an edit icon linked to mode editing page -->
                    <h4 id="createNewModeHeader">{{ mode[2] }}
                        <a href="{{ url_for('mode.edit_mode',  mode_id=mode[0]) }}">
                            <span class="material-symbols-outlined" id="editIcon">
                                edit_square
                            </span>    
                        </a>
                    </h4>
                </div>
            {% endfor %}
        {% endif %}

    </div>
</body>
</html>

app/templates/notes.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <title>NoteMode</title>


    <style>
        /* General styling for the body, we put the styling here because since we are passing information like color and font from 
        previous pages we need them to load on the html rather than an external style sheet. Depeding on your IDE the style tag may look wrong/have red underlines
        but it is not wrong if you have the specific lint installed for jinja */
        body {
            background: {{ color }};
            font-family: {{ font }};
            display: flex;
                flex-direction: column;
                justify-content: center;
                align-items: center;
                height: 100vh; 
                margin: 0; 
        }

        a {
            text-decoration: none;
            color: black;
        }

        .material-symbols-outlined {
            display: inline-block;
            padding: 10px 20px;
            text-align: center;
            text-decoration: none;
            font-size: 16px;
            cursor: pointer;
            border-radius: 5px;

            font-variation-settings:
            'FILL' 0,
            'wght' 400,
            'GRAD' 0,
            'opsz' 24
        }

        .note-tile {
            margin: 4vw; 
            width: 8vw; 
            height: 12vh; 
            flex-shrink: 0;
            background: white; 
            border-radius: 7.5vw;
        }

        .note-icon {
            margin: 4vw; 
            width: 6vw; 
            height: 12vh; 
            flex-shrink: 0;
            background: white; 
            border-radius: 7.5vw;
        }

        .note-list {
            margin: 4vw; 
            width: 8vw; 
            height: 5vh; 
            flex-shrink: 0;
            background: white; 
            border-radius: 7.5vw;
        }

        .notes-header {
            position: absolute;
            top: 1.5vh; 
            left: 2vw; 
            padding: .5vw; 
            color: black;
            text-shadow: 0px 0.4vw 0.4vw rgba(0, 0, 0, 0.25); 
            font-size: 3vw; 
            font-style: normal;
            font-weight: 600;
            line-height: normal;
        }

        .notes-header::before {
            content: "";
            position: absolute;
            bottom: 0;
            left: 0;
            width: 100%;
            height: 0.2vw; 
            background: black;
        }

        .notes-list {
            width: 75vw;
            max-height: 80vh;
            min-height: 80vh;
            overflow-y: auto; 
            flex-shrink: 0;
            background: #a3a1a1;
            border-radius: 10vw;
            display: flex;
            flex-wrap: wrap;  
        }

        .notes-list::-webkit-scrollbar {
            width: 0.5em;
        }

        .navbar {
            height: 100%;
            width: 0;
            position: fixed;
            z-index: 1;
            top: 0;
            left: 0;
            background-color: #FFFFFF;
            overflow-x: hidden;
            transition: 0.5s;
            padding-top: 60px;
        }

        .navbar a {
            padding: 15px 25px;
            text-decoration: none;
            font-size: 25px;
            color: #818181;
            display: block;
            transition: 0.3s;
        }

        .navbar a:hover {
            color: #f1f1f1;
        }

        .open-btn {
            visibility: hidden;
        }

        .navbar .close-btn {
            position: absolute;
            top: 0;
            right: 25px;
            font-size: 30px;
            margin-left: 50px;
        }

        #main {
            transition: margin-left .5s;
        }

        #btnSetting {
            position: absolute;
            font-size: 48px;
            right: 50px;
            top: 40px;
        }

        #btnAdd {
            text-align: center;
            display: flex;
            align-items: center;
            justify-content: center;
            height: 90%;
            font-size: 1.5vw;
        }

        #createNewNoteHeader {
            margin: 1px;
            text-align: center;
            font-size: 15px;
            color: black;
        }

        #editIcon {
            color: white;
        }

        #menu {
            position: absolute;
            visibility: visible;
            font-size: 48px;
            left: 0px;
            top: 0px;
        }

        #editIcon {
            color: black;
        }
    </style>

</head>
<body>

    <!-- Navbar section -->
    <div id="navbar" class="navbar">
        <a href="javascript:void(0)" class="close-btn" onclick="closeNav()">       
            <button class="open-btn" onclick="openNav()">
                <span class="material-symbols-outlined" id="menu">menu</span>
            </button>
        </a>

        <a href="{{ url_for('home') }}">Modes </a>
        <a href="{{ url_for('mode.edit_mode',  mode_id=mode_id) }}">Current Mode Setings</a>
    </div>
    
    <!-- Main content area with menu button -->
    <div id="main">
        <button class="open-btn" onclick="openNav()">
            <span class="material-symbols-outlined" id="menu">menu</span>
        </button>
    </di>
    

    <h1 class="notes-header">{{ name }} </h1>
    

    <a href="{{ url_for('settings.settings_page') }}">
        <span class="material-symbols-outlined" id="btnSetting">settings</span>
    </a>


    <div class="notes-list">
        <!-- Create New Note section -->
        <div class="{{ view }}" id="createNewNotes">
            <a href="{{ url_for('notes.add_note', mode_id=mode_id) }}">
                <span class="material-symbols-outlined" id="btnAdd">add_circle</span> 
            </a>
            <h4 id="createNewNoteHeader"> Create New Note </h4>
            <a ref="{{ url_for('notes.add_note', mode_id=mode_id) }}"></a>
        </div>

        <!-- Loop through existing notes -->
        {% for note in notes %}
            <div class= "{{ view }}">
                <a href="{{ url_for('note.show_note', mode_id=mode_id, note_id=note[0]) }}">
                    <span class="material-symbols-outlined" id="btnAdd"></span> 
                </a>
                <h4 id="createNewNoteHeader">{{ note[2] }}
                    <!-- Edit Note link -->
                    <a href="{{ url_for('notes.edit_note', mode_id=mode_id, note_id=note[0]) }}">
                        <span class="material-symbols-outlined" id="editIcon">
                            edit_square
                        </span>    
                    </a>
                </h4>
            </div>
        {% endfor %}


    </div>

    <!-- Script to handle opening and closing the navbar -->
    <script>
        function openNav() {
            document.getElementById("navbar").style.width = "250px";
            document.getElementById("main").style.marginLeft = "250px";
        }
    
        function closeNav() {
            document.getElementById("navbar").style.width = "0";
            document.getElementById("main").style.marginLeft = "0";
        }
    </script>

</body>
</html>